# Generated by Django 3.0.7 on 2020-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbadge',
            name='badge',
            field=models.ManyToManyField(null=True, to='core.Badge'),
        ),
    ]
