# Generated by Django 3.0.7 on 2020-06-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200622_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, upload_to='badge/'),
        ),
    ]
