# Generated by Django 3.0.7 on 2020-06-26 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_badge_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUID',
            fields=[
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='stack',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
