# Generated by Django 3.0.7 on 2020-07-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200626_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='stack',
        ),
        migrations.AddField(
            model_name='session',
            name='badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Badge'),
        ),
    ]
